
CONFIG_FILE = 'config.json'

RECREATE_DIRS = ['logs']

LOG_FILE_FORMAT = 'logs/{name}.log'
LOG_FILE_MAX_BYTES = 1000 * 1024  # 1024kb
LOG_FILE_BACKUP_COUNT = 5

BINANCE_TEST_ORDER = False

POLL_TIMEOUT = 60

PROCESSING_INTERVAL = 1
POLLING_INTERVAL = 1

KEY_STORE_TABLE_NAME = 'key_store'
DATABASE_PATH = 'bot.db'
